LookCommand Class Reference
class LookCommand used to show information about the current Room or a given Item
Public Member Functions
LookCommand ()
Constructor for LookCommand.
boolean execute (Player player) throws IllegalArgumentException
Saves the information about the current Room or a given Item in the message field.
Private Member Functions
String showItem (Item item)
Return a given Item's description.
Additional Inherited Members
Detailed Description
class LookCommand used to show information about the current Room or a given Item
Author
Rémi Nicole
Definition at line 5 of file LookCommand.java.
Constructor & Destructor Documentation
LookCommand.LookCommand ()
Constructor for LookCommand.
Definition at line 10 of file LookCommand.java.
                        {
    }
Member Function Documentation
boolean LookCommand.execute (Player player) throws IllegalArgumentException
Saves the information about the current Room or a given Item in the message field.
Parameters
player The player that called this command
Exceptions
IllegalArgumentException When the user typed a name other than any of the items in the Player's or the Room's inventory
Returns
False because it is not the quit command
Definition at line 20 of file LookCommand.java.
References Command.getParameter(), Command.hasParameter(), Command.setMessage(), and showItem().
                                                                          {
        if(hasParameter()) {
            if(player.getCurrentRoom().hasItem(getParameter())) {
                setMessage(
                        showItem(player.getCurrentRoom().getItem(
      getParameter()))
                        );
            } else if (player.hasItem(getParameter())) {
                setMessage(
                        showItem(player.getItem(getParameter()))
                        );
            } else
                throw new IllegalArgumentException("I'm not sure you want to look
       at that.");
        } else
            setMessage(player.getCurrentRoom().getLongDescription());
        return false;
    }
String LookCommand.showItem (Item item) [private]
Return a given Item's description.
Parameters
item The item for which we want the description
Returns
The item's description
Definition at line 42 of file LookCommand.java.
Referenced by execute().
                                       {
        return "This is " + item.getDescription() + ".";
    }
The documentation for this class was generated from the following file:
LookCommand.java