TestCommand Class Reference
class TestCommand used to test series of commands
Public Member Functions
TestCommand ()
Constructor for TestCommand.
boolean execute (Player player) throws NoArgumentException,IllegalArgumentException
Test series of Commands stored in a .test file and store the messages in the message field.
Additional Inherited Members
Detailed Description
class TestCommand used to test series of commands
Author
Rémi Nicole
Definition at line 9 of file TestCommand.java.
Constructor & Destructor Documentation
TestCommand.TestCommand ()
Constructor for TestCommand.
Definition at line 14 of file TestCommand.java.
                        {
    }
Member Function Documentation
boolean TestCommand.execute (Player player) throws NoArgumentException,IllegalArgumentException
Test series of Commands stored in a .test file and store the messages in the message field.
Each command in the test file must be separated by an end-of-line character
Parameters
player The player that called this command
Exceptions
NoArgumentException When the user typed the command without parameter
IllegalArgumentException When the user typed a name other than any of the .test files in the directory
Returns
False because it is not the quit command
Definition at line 26 of file TestCommand.java.
References Command.getMessage(), Command.getParameter(), Command.hasParameter(), and Command.setMessage().
                                                                                              {
        setMessage("");
        if(hasParameter()) {
            try {
                Scanner s = new Scanner(new File(getParameter() + ".test"));
                while (s.hasNextLine()) {
                    String commandLine = s.nextLine();
                    Command testedCommand = Parser.getCommand(commandLine);
                    try {
                        testedCommand.execute(player);
                        if(testedCommand.hasMessage())
                            setMessage(getMessage() + "\n" + "Command: " + commandLine
      + "\n"
                                    + testedCommand.getMessage());
                    } catch (NoArgumentException e) {
                        setMessage(getMessage() + "\n" + "Command: " + commandLine + "
      \n"
                                + e.getMessage());
                    } catch (IllegalArgumentException e) {
                        setMessage(getMessage() + "\n" + "Command: " + commandLine + "
      \n"
                                + e.getMessage());
                    } catch(UnauthorizedException e) {
                        setMessage(getMessage() + "\n" + "Command: " + commandLine + "
      \n"
                                + e.getMessage());
                    }
                }
                s.close();
            } catch(FileNotFoundException e) {
                throw new IllegalArgumentException("No such test");
            }
        } else
            throw new NoArgumentException("What do you want to test?");
        return false;
    }
The documentation for this class was generated from the following file:
TestCommand.java