UserInterface Class Reference
Class handling the game's user interface.
Public Member Functions
UserInterface (GameEngine gameEngine)
UserInterface class constructor.
void setCommandsLeft (int commandsLeft)
Change the text for the commands left JLabel.
void print (String text)
Print the given text in the text area.
void println (String text)
Print the given text plus a newline in the text area.
void showImage (String imageName)
Show the image corresponding to the path of the image.
void enable (boolean on)
Enable or disable the input field.
void actionPerformed (ActionEvent e)
Actionlistener for the textfield.
Private Member Functions
void createGUI ()
Create the user interface.
void processCommand ()
Process the command inside the text entry.
Private Attributes
GameEngine engine
Gameplay handler.
JFrame myFrame
JFrame containing the graphics.
JTextField entryField
Field where the user will put its commands.
JTextArea log
Container for the displayed text.
JLabel image
Container for the image of the room.
JLabel commandsLeftLabel
Container for the String of commands left.
Detailed Description
Class handling the game's user interface.
Author
Rémi NICOLE
Definition at line 11 of file UserInterface.java.
Constructor & Destructor Documentation
UserInterface.UserInterface (GameEngine gameEngine)
UserInterface class constructor.
Parameters
gameEngine The gameplay GameEngine object.
Definition at line 47 of file UserInterface.java.
References createGUI(), and engine.
                                                {
        engine = gameEngine;
        createGUI();
    }
Member Function Documentation
void UserInterface.actionPerformed (ActionEvent e)
Actionlistener for the textfield.
Parameters
e Event
Definition at line 182 of file UserInterface.java.
References processCommand().
                                               {
        if(e.getActionCommand().equals("↑")) {
            engine.processCommand("go north");
        } else if(e.getActionCommand().equals("↓")) {
            engine.processCommand("go south");
        } else if(e.getActionCommand().equals("←")) {
            engine.processCommand("go west");
        } else if(e.getActionCommand().equals("→")) {
            engine.processCommand("go east");
        } else if(e.getActionCommand().equals("?")) {
            engine.processCommand("help");
        } else {
            processCommand();
        }
    }
void UserInterface.createGUI () [private]
Create the user interface.
Definition at line 106 of file UserInterface.java.
References commandsLeftLabel, entryField, image, log, and myFrame.
Referenced by UserInterface().
                             {
        myFrame = new JFrame("Bad Philophobia");
        entryField = new JTextField(34);
        log = new JTextArea();
        log.setEditable(false);
        JScrollPane listScroller = new JScrollPane(log);
        listScroller.setPreferredSize(new Dimension(200, 200));
        listScroller.setMinimumSize(new Dimension(100, 100));
        JPanel panel = new JPanel();
        JPanel buttonsPanel = new JPanel();
        buttonsPanel.setPreferredSize(new Dimension(200,200));
        image = new JLabel();
        JButton buttonNorth = new JButton("↑");
        buttonNorth.addActionListener(this);
        JButton buttonSouth = new JButton("↓");
        buttonSouth.addActionListener(this);
        JButton buttonEast = new JButton("→");
        buttonEast.addActionListener(this);
        JButton buttonWest = new JButton("←");
        buttonWest.addActionListener(this);
        JButton buttonHelp = new JButton("?");
        buttonHelp.addActionListener(this);
        JButton buttonReturn = new JButton("⏎");
        buttonReturn.addActionListener(this);
        buttonsPanel.setLayout(new GridLayout(3,3));
        buttonsPanel.add(new JButton(""));
        buttonsPanel.add(buttonNorth);
        buttonsPanel.add(new JButton(""));
        buttonsPanel.add(buttonWest);
        buttonsPanel.add(buttonHelp);
        buttonsPanel.add(buttonEast);
        buttonsPanel.add(buttonReturn);
        buttonsPanel.add(buttonSouth);
        buttonsPanel.add(new JButton(""));
        panel.setLayout(new BorderLayout());
        panel.add(image, BorderLayout.NORTH);
        panel.add(listScroller, BorderLayout.CENTER);
        panel.add(buttonsPanel, BorderLayout.EAST);
        JPanel bottomPanel = new JPanel();
        bottomPanel.setLayout(new BorderLayout());
        bottomPanel.add(entryField, BorderLayout.CENTER);
        commandsLeftLabel = new JLabel();
        bottomPanel.add(commandsLeftLabel, BorderLayout.EAST);
        panel.add(bottomPanel, BorderLayout.SOUTH);
        myFrame.getContentPane().add(panel, BorderLayout.CENTER);
        myFrame.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                System.exit(0);
            }
        });
        entryField.addActionListener(this);
        myFrame.pack();
        myFrame.setVisible(true);
        entryField.requestFocus();
    }
void UserInterface.enable (boolean on)
Enable or disable the input field.
Parameters
on True to activate, False to deactivate
Definition at line 97 of file UserInterface.java.
                                   {
        entryField.setEditable(on);
        if(!on)
            entryField.getCaret().setBlinkRate(0);
    }
void UserInterface.print (String text)
Print the given text in the text area.
Parameters
text Text to display
Definition at line 64 of file UserInterface.java.
                                   {
        log.append(text);
        log.setCaretPosition(log.getDocument().getLength());
    }
void UserInterface.println (String text)
Print the given text plus a newline in the text area.
Parameters
text Text to display
Definition at line 73 of file UserInterface.java.
Referenced by GameEngine.processCommand().
                                     {
        log.append(text + "\n");
        log.setCaretPosition(log.getDocument().getLength());
    }
void UserInterface.processCommand () [private]
Process the command inside the text entry.
Definition at line 201 of file UserInterface.java.
Referenced by actionPerformed().
                                  {
        boolean finished = false;
        String input = entryField.getText();
        entryField.setText("");
        engine.processCommand(input);
    }
void UserInterface.setCommandsLeft (int commandsLeft)
Change the text for the commands left JLabel.
Parameters
commandsLeft The number of commands left
Definition at line 56 of file UserInterface.java.
                                                  {
        commandsLeftLabel.setText(" Commands left: " + commandsLeft + " ");
    }
void UserInterface.showImage (String imageName)
Show the image corresponding to the path of the image.
Parameters
imageName The path of the image
Definition at line 82 of file UserInterface.java.
                                            {
        URL imageURL = this.getClass().getClassLoader().getResource(imageName);
        if(imageURL == null)
            System.out.println("image not found");
        else {
            ImageIcon icon = new ImageIcon(imageURL);
            image.setIcon(icon);
            myFrame.pack();
        }
    }
Member Data Documentation
JLabel UserInterface.commandsLeftLabel [private]
Container for the String of commands left.
Definition at line 41 of file UserInterface.java.
Referenced by createGUI().
GameEngine UserInterface.engine [private]
Gameplay handler.
Definition at line 16 of file UserInterface.java.
Referenced by UserInterface().
JTextField UserInterface.entryField [private]
Field where the user will put its commands.
Definition at line 26 of file UserInterface.java.
Referenced by createGUI().
JLabel UserInterface.image [private]
Container for the image of the room.
Definition at line 36 of file UserInterface.java.
Referenced by createGUI().
JTextArea UserInterface.log [private]
Container for the displayed text.
Definition at line 31 of file UserInterface.java.
Referenced by createGUI().
JFrame UserInterface.myFrame [private]
JFrame containing the graphics.
Definition at line 21 of file UserInterface.java.
Referenced by createGUI().
The documentation for this class was generated from the following file:
UserInterface.java