pkg_commands.ThrowCommand Class Reference
class ThrowCommand used to make the player throw an Item
Public Member Functions
ThrowCommand ()
Constructor for ThrowCommand.
boolean execute (Player player) throws NoArgumentException,IllegalArgumentException
Throw the Item through it's name in the parameter field.
Additional Inherited Members
Detailed Description
class ThrowCommand used to make the player throw an Item
Author
Rémi Nicole
Definition at line 12 of file ThrowCommand.java.
Constructor & Destructor Documentation
pkg_commands.ThrowCommand.ThrowCommand ()
Constructor for ThrowCommand.
Definition at line 17 of file ThrowCommand.java.
                         {
    }
Member Function Documentation
boolean pkg_commands.ThrowCommand.execute (Player player) throws NoArgumentException,IllegalArgumentException
Throw the Item through it's name in the parameter field.
Parameters
player The player that called this command
Exceptions
NoArgumentException When the user typed the command without parameter
IllegalArgumentException When the user typed a name other than any of the items in the Player's inventory
Returns
False because it is not the quit command or true if the player won the game
Definition at line 28 of file ThrowCommand.java.
References pkg_commands.Command.getParameter(), pkg_commands.Command.hasParameter(), and pkg_commands.Command.setMessage().
                                                                                              {
        if(hasParameter()) {
            if(player.hasItem(getParameter())){
                if(getParameter().equals("snowball")) {
                    // Has thrown the snowball and is in the alpine tundra Room
                    if(player.getCurrentRoom() == GameEngine.getRooms().get(3) && player.threwSnowball()) {
                        setMessage("Snowball!!! A snowball!!! (The robot tries to fetch the
       snowball but falls into the water and \"dies\".)");
                        // Won
                        return true;
                    } else {
                        setMessage("Snowball!!! A snowball!!! (The robot fetches the snowball but
       melts it because of it's circuits)\n*Sob*, my snowball...");
                        player.eatObject("snowball");
                        player.throwSnowball();
                    }
                } else {
                    player.eatObject(getParameter());
                    setMessage("Stop throwing everything away! I hope it's the last time.");
                }
            } else
                throw new IllegalArgumentException("If you want to throw that, you may have a mental
       disorder. As expected.");
        } else
            throw new NoArgumentException("Yes, I'm gonna throw a fit.");
        return false;
    }
The documentation for this class was generated from the following file:
pkg_commands/ThrowCommand.java