pkg_commands.GoCommand Class Reference
class GoCommand used to make the player go to a given Room.
Public Member Functions
GoCommand ()
Constructor for GoCommand.
boolean execute (Player player) throws NoArgumentException,pkg_exceptions.IllegalArgumentException,UnauthorizedException
Make the player go to the Room through it's direction in the parameter field.
Protected Member Functions
void goRoomCheck (Room room, Player player, boolean back) throws pkg_exceptions.IllegalArgumentException,UnauthorizedException
Check if the wanted Room is connected to the current Room and go to this room.
void goRoomNoCheck (Room room, Player player, boolean back) throws pkg_exceptions.IllegalArgumentException
Go to the Room without checking.
Room getRandomRoom ()
Get a random room from the GameEngin list or Room.
Detailed Description
class GoCommand used to make the player go to a given Room.
Author
Rémi Nicole
Definition at line 15 of file GoCommand.java.
Constructor & Destructor Documentation
pkg_commands.GoCommand.GoCommand ()
Constructor for GoCommand.
Definition at line 20 of file GoCommand.java.
                       {
    }
Member Function Documentation
boolean pkg_commands.GoCommand.execute (Player player) throws NoArgumentException,pkg_exceptions.IllegalArgumentException,UnauthorizedException
Make the player go to the Room through it's direction in the parameter field.
Parameters
player The player that called this command
Exceptions
NoArgumentException When the user typed the command without parameter
IllegalArgumentException When the user typed a parameter other than an available exit direction
UnauthorizedException When the user isn't allowed to go to the given Room
Returns
False because it is not the quit command
Definition at line 32 of file GoCommand.java.
References pkg_commands.Command.getParameter(), pkg_commands.GoCommand.getRandomRoom(), pkg_commands.GoCommand.goRoomCheck(), pkg_commands.GoCommand.goRoomNoCheck(), pkg_commands.Command.hasParameter(), and pkg_commands.Command.setMessage().
                                                                                                           
                              {
        setMessage("");
        // Check if it is the random Room (which is the first room in the gamesRoom GameEngine ArrayList)
        if(player.getCurrentRoom() != GameEngine.getRooms().get(0)) {
            if(hasParameter()) {
                goRoomCheck(player.getCurrentRoom().getExit(
      getParameter()), player, false);
            } else {
                throw new NoArgumentException("If you were clever, I would have thought
       that it was a existential question.\nBut that is not the case and I cannot allow you to go nowhere");
            }
        } else {
            setMessage("Geronimoooo !\n");
            goRoomNoCheck(getRandomRoom(), player, false);
        }
        return false;
    }
Room pkg_commands.GoCommand.getRandomRoom () [protected]
Get a random room from the GameEngin list or Room.
Returns
A random room
Definition at line 87 of file GoCommand.java.
Referenced by pkg_commands.GoCommand.execute().
                                   {
        return GameEngine.getRooms().get((new Random()).nextInt(GameEngine.getRooms().size() - 1) + 1);
    }
void pkg_commands.GoCommand.goRoomCheck (Room room, Player player, boolean back) throws pkg_exceptions.IllegalArgumentException,UnauthorizedException [protected]
Check if the wanted Room is connected to the current Room and go to this room.
Parameters
room Room where the user want to go
player The player that called this command
back true if it is called via the 'back' command
Exceptions
IllegalArgumentException When the user tries to go to null
UnauthorizedException When the user isn't allowed to go to the given Room
Definition at line 56 of file GoCommand.java.
References pkg_commands.GoCommand.goRoomNoCheck().
Referenced by pkg_commands.GoCommand.execute().
                                                                                                           
                                       {
        if(player.getCurrentRoom().isExit(room)) {
            goRoomNoCheck(room, player, back);
        } else {
            throw new UnauthorizedException("I'm sorry but you can't pass through
       walls.");
        }
    }
void pkg_commands.GoCommand.goRoomNoCheck (Room room, Player player, boolean back) throws pkg_exceptions.IllegalArgumentException [protected]
Go to the Room without checking.
Parameters
room Room where the user want to go
player The player that called this command
back true if it is called via the 'back' command
Exceptions
IllegalArgumentException When the user tries to go to null
Definition at line 71 of file GoCommand.java.
References pkg_commands.Command.getMessage(), pkg_commands.Command.hasMessage(), and pkg_commands.Command.setMessage().
Referenced by pkg_commands.GoCommand.execute(), pkg_commands.GoCommand.goRoomCheck(), and pkg_commands.BeamerCommand.teleport().
                                                                                                           
                   {
        if(room != null) {
            if(!back)
                player.pushForward();
            else
                player.popPreviousRooms();
            player.goRoom(room);
            setMessage(((hasMessage()) ? getMessage() + "\n" : "") + room.
      getLongDescription());
        } else
            throw new pkg_exceptions.IllegalArgumentException("This
       is a wall, not a door!");
    }
The documentation for this class was generated from the following file:
pkg_commands/GoCommand.java