DropCommand Class Reference
class DropCommand used to make the player drop an Item
Public Member Functions
DropCommand ()
Constructor for DropCommand.
boolean execute (Player player) throws NoArgumentException,IllegalArgumentException
Drop the Item through it's name in the parameter field.
Additional Inherited Members
Detailed Description
class DropCommand used to make the player drop an Item
Author
Rémi Nicole
Definition at line 5 of file DropCommand.java.
Constructor & Destructor Documentation
DropCommand.DropCommand ()
Constructor for DropCommand.
Definition at line 10 of file DropCommand.java.
                        {
    }
Member Function Documentation
boolean DropCommand.execute (Player player) throws NoArgumentException,IllegalArgumentException
Drop the Item through it's name in the parameter field.
Parameters
player The player that called this command
Exceptions
NoArgumentException When the user typed the command without parameter
IllegalArgumentException When the user typed a name other than any of the items in the Player's inventory
Returns
False because it is not the quit command
Definition at line 21 of file DropCommand.java.
References Command.getParameter(), Command.hasParameter(), and Command.setMessage().
                                                                                              {
        if(hasParameter()) {
            if(player.hasItem(getParameter())){
                player.dropObject(getParameter());
                setMessage("Oh, dear. He took a" + (((new String("aeiouy")).contains(
      getParameter().substring(0,1)))? "n " : " ") + getParameter() + ".");
            } else
                throw new IllegalArgumentException("If you want to drop that, you
       may have a mental disorder. As expected.");
        } else
            throw new NoArgumentException("I agree. We both want you to drop dead.");
        return false;
    }
The documentation for this class was generated from the following file:
DropCommand.java