HelpCommand Class Reference
class HelpCommand used to print the help
Public Member Functions
HelpCommand ()
Constructor for HelpCommand.
boolean execute (Player player)
Saves user's help in the parameter field.
Private Attributes
int helpCount
Help query counter.
Additional Inherited Members
Detailed Description
class HelpCommand used to print the help
Author
Rémi Nicole
Definition at line 5 of file HelpCommand.java.
Constructor & Destructor Documentation
HelpCommand.HelpCommand ()
Constructor for HelpCommand.
Definition at line 18 of file HelpCommand.java.
References helpCount.
                        {
        helpCount = 0;
    }
Member Function Documentation
boolean HelpCommand.execute (Player player)
Saves user's help in the parameter field.
It really shows help if the user asked for more than once the help.
Parameters
player The player that called this command
Returns
False because it is not the quit command
Definition at line 28 of file HelpCommand.java.
References Command.getMessage(), helpCount, Command.setMessage(), and Parser.showCommands().
                                          {
        setMessage("");
        if(helpCount == 0) {
            setMessage("Help ? Who needs help ? Only the weak ones.");
            ++helpCount;
        } else {
            if(helpCount == 1){
                setMessage("All right, all right! If you insist...\n");
                ++helpCount;
            }
            setMessage(getMessage() + "What you can do is: " +
      Parser.showCommands() + "\n"
                    + "That will be all.");
        }
        return false;
    }
Member Data Documentation
int HelpCommand.helpCount [private]
Help query counter.
It is equal to 0 if the user did not ask for help, 1 if the user asked once the help and 2 if the user asked twice or more for the help
Definition at line 13 of file HelpCommand.java.
Referenced by execute(), and HelpCommand().
The documentation for this class was generated from the following file:
HelpCommand.java