Command Class Reference
Class used to handle a command of one or two words.
Public Member Functions
String getParameter ()
Parameter field getter.
void setParameter (String parameter)
Parameter field setter.
boolean hasParameter ()
Return true if the parameter is null.
String getMessage ()
Message field getter.
boolean hasMessage ()
Return true if the message is equal to null or ``.
abstract boolean execute (Player player) throws NoArgumentException,IllegalArgumentException,UnauthorizedException
Process the command.
Protected Member Functions
void setMessage (String message)
Message field setter.
Private Attributes
String parameter
Parameter for the command.
String message
Message to be printed.
Detailed Description
Class used to handle a command of one or two words.
Author
Rémi NICOLE
Definition at line 5 of file Command.java.
Member Function Documentation
abstract boolean Command.execute (Player player) throws NoArgumentException,IllegalArgumentException,UnauthorizedException [abstract]
Process the command.
Parameters
player The player that called this command
Exceptions
NoArgumentException When the command needed a parameter but the user didn't specify one
IllegalArgumentException When the user typed a parameter other than the correct ones
UnauthorizedException When the user isn't allowed to do this action
String Command.getMessage ()
Message field getter.
Returns
The message to print to the user
Definition at line 57 of file Command.java.
References message.
Referenced by TestCommand.execute(), HelpCommand.execute(), and GoCommand.goRoomNoCheck().
                               {
        return (message == null)? "" : message;
    }
String Command.getParameter ()
Parameter field getter.
Returns
The parameter given by the user
Definition at line 25 of file Command.java.
References parameter.
Referenced by LookCommand.execute(), DropCommand.execute(), GoCommand.execute(), TakeCommand.execute(), EatCommand.execute(), BeamerCommand.execute(), and TestCommand.execute().
                                 {
        return parameter;
    }
boolean Command.hasMessage ()
Return true if the message is equal to null or ``.
Returns
True if the message is equal to null or ``
Definition at line 65 of file Command.java.
References message.
Referenced by GoCommand.goRoomNoCheck().
                                {
        return (message == null) ? false : !message.equals("");
    }
boolean Command.hasParameter ()
Return true if the parameter is null.
Returns
True if the parameter is null
Definition at line 41 of file Command.java.
References parameter.
Referenced by LookCommand.execute(), DropCommand.execute(), GoCommand.execute(), TakeCommand.execute(), EatCommand.execute(), BeamerCommand.execute(), and TestCommand.execute().
                                  {
        return (parameter != null);
    }
void Command.setMessage (String message) [protected]
Message field setter.
Parameters
message The message to set
Definition at line 49 of file Command.java.
References message.
Referenced by BeamerCommand.charge(), InventoryCommand.execute(), CreditsCommand.execute(), LookCommand.execute(), DropCommand.execute(), TakeCommand.execute(), GoCommand.execute(), EatCommand.execute(), TestCommand.execute(), HelpCommand.execute(), GoCommand.goRoomNoCheck(), and BeamerCommand.teleport().
                                              {
        this.message = message;
    }
void Command.setParameter (String parameter)
Parameter field setter.
Parameters
parameter The parameter to set
Definition at line 33 of file Command.java.
References parameter.
                                               {
        this.parameter = parameter;
    }
Member Data Documentation
String Command.message [private]
Message to be printed.
This message is printed if and only if the command was successfully processed
Definition at line 19 of file Command.java.
Referenced by getMessage(), hasMessage(), and setMessage().
String Command.parameter [private]
Parameter for the command.
It equals to null if there is no parameter.
Definition at line 12 of file Command.java.
Referenced by getParameter(), hasParameter(), and setParameter().
The documentation for this class was generated from the following file:
Command.java