pkg_commands.LookCommand Class Reference
class LookCommand used to show information about the current Room or a given Item
Public Member Functions
LookCommand ()
Constructor for LookCommand.
boolean execute (Player player) throws IllegalArgumentException
Saves the information about the current Room or a given Item in the message field.
Private Member Functions
String showItem (Item item)
Return a given Item's description.
Additional Inherited Members
Detailed Description
class LookCommand used to show information about the current Room or a given Item
Author
Rémi Nicole
Definition at line 11 of file LookCommand.java.
Constructor & Destructor Documentation
pkg_commands.LookCommand.LookCommand ()
Constructor for LookCommand.
Definition at line 16 of file LookCommand.java.
                        {
    }
Member Function Documentation
boolean pkg_commands.LookCommand.execute (Player player) throws IllegalArgumentException
Saves the information about the current Room or a given Item in the message field.
Parameters
player The player that called this command
Exceptions
IllegalArgumentException When the user typed a name other than any of the items in the Player's or the Room's inventory
Returns
False because it is not the quit command
Definition at line 26 of file LookCommand.java.
References pkg_commands.Command.getParameter(), pkg_commands.Command.hasParameter(), pkg_commands.Command.setMessage(), and pkg_commands.LookCommand.showItem().
                                                                          {
        if(hasParameter()) {
            if(player.getCurrentRoom().hasItem(getParameter())) {
                setMessage(
                        showItem(player.getCurrentRoom().getItem(
      getParameter()))
                        );
            } else if (player.hasItem(getParameter())) {
                setMessage(
                        showItem(player.getItem(getParameter()))
                        );
            } else
                throw new IllegalArgumentException("I'm not sure you want to look at that.");
        } else
            setMessage(player.getCurrentRoom().getLongDescription());
        return false;
    }
String pkg_commands.LookCommand.showItem (Item item) [private]
Return a given Item's description.
Parameters
item The item for which we want the description
Returns
The item's description
Definition at line 48 of file LookCommand.java.
Referenced by pkg_commands.LookCommand.execute().
                                       {
        return "This is " + item.getDescription() + ".";
    }
The documentation for this class was generated from the following file:
pkg_commands/LookCommand.java