TakeCommand Class Reference
class TakeCommand used to make the Player take an Item
Public Member Functions
TakeCommand ()
Constructor for TakeCommand.
boolean execute (Player player) throws NoArgumentException,IllegalArgumentException,UnauthorizedException
Make the player take an Item.
Additional Inherited Members
Detailed Description
class TakeCommand used to make the Player take an Item
Author
Rémi Nicole
Definition at line 5 of file TakeCommand.java.
Constructor & Destructor Documentation
TakeCommand.TakeCommand ()
Constructor for TakeCommand.
Definition at line 10 of file TakeCommand.java.
                        {
    }
Member Function Documentation
boolean TakeCommand.execute (Player player) throws NoArgumentException,IllegalArgumentException,UnauthorizedException
Make the player take an Item.
Parameters
player The player that called this command
Exceptions
NoArgumentException When the user typed the command without parameter
IllegalArgumentException When the user typed a name other than any of the items in the Room's inventory
UnauthorizedException When the user tries to take too much object considering their weights
Returns
False because it is not the quit command
Definition at line 22 of file TakeCommand.java.
References Command.getParameter(), Command.hasParameter(), and Command.setMessage().
                                                                                                           
               {
        if(hasParameter()) {
            if(player.getCurrentRoom().hasItem(getParameter())) {
                if(player.canCarry(player.getCurrentRoom().getItem(
      getParameter()))) {
                    player.takeObject(player.getCurrentRoom().getItem(
      getParameter()));
                    setMessage("Oh, dear. He took a" + (((new String("aeiouy")).contains(
      getParameter().substring(0,1)))? "n " : " ") + getParameter() + ".");
                } else
                    throw new UnauthorizedException("That's way too much items for
       you. I know, humans are weak.");
            } else
                throw new IllegalArgumentException("I'm not sure you want to take
       that.");
        } else
            throw new NoArgumentException("Wanna take a photo?");
        return false;
    }
The documentation for this class was generated from the following file:
TakeCommand.java