GoCommand Class Reference
class GoCommand used to make the player go to a given Room.
Public Member Functions
GoCommand ()
Constructor for GoCommand.
boolean execute (Player player) throws NoArgumentException,IllegalArgumentException,UnauthorizedException
Make the player go to the Room through it's direction in the parameter field.
Protected Member Functions
void goRoomCheck (Room room, Player player, boolean back) throws IllegalArgumentException,UnauthorizedException
Check if the wanted Room is connected to the current Room and go to this room.
void goRoomNoCheck (Room room, Player player, boolean back) throws IllegalArgumentException
Go to the Room without checking.
Detailed Description
class GoCommand used to make the player go to a given Room.
Author
Rémi Nicole
Definition at line 5 of file GoCommand.java.
Constructor & Destructor Documentation
GoCommand.GoCommand ()
Constructor for GoCommand.
Definition at line 10 of file GoCommand.java.
                      {
    }
Member Function Documentation
boolean GoCommand.execute (Player player) throws NoArgumentException,IllegalArgumentException,UnauthorizedException
Make the player go to the Room through it's direction in the parameter field.
Parameters
player The player that called this command
Exceptions
NoArgumentException When the user typed the command without parameter
IllegalArgumentException When the user typed a parameter other than an available exit direction
UnauthorizedException When the user isn't allowed to go to the given Room
Returns
False because it is not the quit command
Definition at line 22 of file GoCommand.java.
References Command.getParameter(), goRoomCheck(), Command.hasParameter(), and Command.setMessage().
                                                                                                           
               {
        setMessage("");
        if(hasParameter()) {
            goRoomCheck(player.getCurrentRoom().getExit(
      getParameter()), player, false);
        } else {
            throw new NoArgumentException("If you were clever, I would have thought that
       it was a existential question.\nBut that is not the case and I cannot allow you to go nowhere");
        }
        return false;
    }
void GoCommand.goRoomCheck (Room room, Player player, boolean back) throws IllegalArgumentException,UnauthorizedException [protected]
Check if the wanted Room is connected to the current Room and go to this room.
Parameters
room Room where the user want to go
player The player that called this command
back true if it is called via the 'back' command
Exceptions
IllegalArgumentException When the user tries to go to null
UnauthorizedException When the user isn't allowed to go to the given Room
Definition at line 40 of file GoCommand.java.
References goRoomNoCheck().
Referenced by execute().
                                                                                                           
                        {
        if(player.getCurrentRoom().isExit(room)) {
            goRoomNoCheck(room, player, back);
        } else {
            throw new UnauthorizedException("I'm sorry but you can't pass through
       walls.");
        }
    }
void GoCommand.goRoomNoCheck (Room room, Player player, boolean back) throws IllegalArgumentException [protected]
Go to the Room without checking.
Parameters
room Room where the user want to go
player The player that called this command
back true if it is called via the 'back' command
Exceptions
IllegalArgumentException When the user tries to go to null
Definition at line 55 of file GoCommand.java.
References Command.getMessage(), Command.hasMessage(), and Command.setMessage().
Referenced by goRoomCheck(), and BeamerCommand.teleport().
                                                                                                         {
        if(room != null) {
            if(!back)
                player.pushForward();
            else
                player.popPreviousRooms();
            player.goRoom(room);
            setMessage(((hasMessage()) ? getMessage() + "\n" : "") + room.
      getLongDescription());
        } else
            throw new IllegalArgumentException("This is a wall, not a door!");
    }
The documentation for this class was generated from the following file:
GoCommand.java