pkg_game.UserInterface Class Reference
Class handling the game's user interface.
Public Member Functions
UserInterface (GameEngine gameEngine)
UserInterface class constructor.
void setCommandsLeft (int commandsLeft)
Change the text for the commands left JLabel.
void print (String text)
Print the given text in the text area.
void println (String text)
Print the given text plus a newline in the text area.
void showImage (String imageName)
Show the image corresponding to the path of the image.
void enable (boolean on)
Enable or disable the input field.
void actionPerformed (ActionEvent e)
Actionlistener for the textfield.
Private Member Functions
void createGUI ()
Create the user interface.
void processCommand ()
Process the command inside the text entry.
Private Attributes
GameEngine engine
Gameplay handler.
JFrame myFrame
JFrame containing the graphics.
JTextField entryField
Field where the user will put its commands.
JTextArea log
Container for the displayed text.
JLabel image
Container for the image of the room.
JLabel commandsLeftLabel
Container for the String of commands left.
HashMap< JButton, String > buttons
The list of buttons in the user interface.
Detailed Description
Class handling the game's user interface.
Author
Rémi NICOLE
Definition at line 15 of file UserInterface.java.
Constructor & Destructor Documentation
pkg_game.UserInterface.UserInterface (GameEngine gameEngine)
UserInterface class constructor.
Parameters
gameEngine The gameplay GameEngine object.
Definition at line 56 of file UserInterface.java.
References pkg_game.UserInterface.buttons, pkg_game.UserInterface.createGUI(), and pkg_game.UserInterface.engine.
                                                {
        engine = gameEngine;
        buttons = new HashMap<JButton, String>();
        createGUI();
    }
Member Function Documentation
void pkg_game.UserInterface.actionPerformed (ActionEvent e)
Actionlistener for the textfield.
Parameters
e Event
Definition at line 214 of file UserInterface.java.
References pkg_game.UserInterface.entryField, and pkg_game.UserInterface.processCommand().
                                               {
        if(e.getSource() == entryField) {
            processCommand();
            return;
        }
        String command = buttons.get(((JButton)e.getSource()));
        if(command == null)
            processCommand();
        else if(command.equals(""))
            processCommand();
        else
            engine.processCommand(command);
    }
void pkg_game.UserInterface.createGUI () [private]
Create the user interface.
Definition at line 123 of file UserInterface.java.
References pkg_game.UserInterface.buttons, pkg_game.UserInterface.commandsLeftLabel, pkg_game.UserInterface.entryField, pkg_game.UserInterface.image, pkg_game.UserInterface.log, and pkg_game.UserInterface.myFrame.
Referenced by pkg_game.UserInterface.UserInterface().
                             {
        myFrame = new JFrame("Bad Philophobia");
        entryField = new JTextField(34);
        log = new JTextArea();
        log.setEditable(false);
        JScrollPane listScroller = new JScrollPane(log);
        listScroller.setPreferredSize(new Dimension(200, 200));
        listScroller.setMinimumSize(new Dimension(100, 100));
        JPanel panel = new JPanel();
        JPanel buttonsPanel = new JPanel();
        buttonsPanel.setPreferredSize(new Dimension(200,200));
        image = new JLabel();
        Font buttonsFont = new Font(Font.SANS_SERIF, Font.PLAIN, 30);
        JButton buttonNorth = new JButton(new ImageIcon("Images/sprites/gonorth.png"));
        buttons.put(buttonNorth, "go north");
        JButton buttonSouth = new JButton(new ImageIcon("Images/sprites/gosouth.png"));
        buttons.put(buttonSouth, "go south");
        JButton buttonEast = new JButton(new ImageIcon("Images/sprites/goeast.png"));
        buttons.put(buttonEast, "go east");
        JButton buttonWest = new JButton(new ImageIcon("Images/sprites/gowest.png"));
        buttons.put(buttonWest, "go west");
        JButton buttonHelp = new JButton(new ImageIcon("Images/sprites/help.png"));
        buttons.put(buttonHelp, "help");
        JButton buttonReturn = new JButton(new ImageIcon("Images/sprites/enter.png"));
        buttons.put(buttonReturn, "");
        JButton buttonCharge = new JButton(new ImageIcon("Images/sprites/charge.png"));
        buttons.put(buttonCharge, "beamer charge");
        JButton buttonTeleport = new JButton(new ImageIcon("Images/sprites/teleport.png"));
        buttons.put(buttonTeleport, "beamer teleport");
        JButton buttonBack = new JButton(new ImageIcon("Images/sprites/back.png"));
        buttons.put(buttonBack, "back");
        for (JButton button : buttons.keySet()) {
            button.addActionListener(this);
        }
        buttonsPanel.setLayout(new GridLayout(3,3));
        buttonsPanel.add(buttonBack);
        buttonsPanel.add(buttonNorth);
        buttonsPanel.add(buttonCharge);
        buttonsPanel.add(buttonWest);
        buttonsPanel.add(buttonHelp);
        buttonsPanel.add(buttonEast);
        buttonsPanel.add(buttonReturn);
        buttonsPanel.add(buttonSouth);
        buttonsPanel.add(buttonTeleport);
        panel.setLayout(new BorderLayout());
        panel.add(image, BorderLayout.NORTH);
        panel.add(listScroller, BorderLayout.CENTER);
        panel.add(buttonsPanel, BorderLayout.EAST);
        JPanel bottomPanel = new JPanel();
        bottomPanel.setLayout(new BorderLayout());
        bottomPanel.add(entryField, BorderLayout.CENTER);
        commandsLeftLabel = new JLabel();
        bottomPanel.add(commandsLeftLabel, BorderLayout.EAST);
        panel.add(bottomPanel, BorderLayout.SOUTH);
        myFrame.getContentPane().add(panel, BorderLayout.CENTER);
        myFrame.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                System.exit(0);
            }
        });
        entryField.addActionListener(this);
        myFrame.pack();
        myFrame.setVisible(true);
        entryField.requestFocus();
    }
void pkg_game.UserInterface.enable (boolean on)
Enable or disable the input field.
Parameters
on True to activate, False to deactivate
Definition at line 107 of file UserInterface.java.
References pkg_game.UserInterface.buttons.
                                   {
        entryField.setEditable(on);
        entryField.setEnabled(on);
        if(!on)
            entryField.getCaret().setBlinkRate(0);
        for (JButton button : buttons.keySet()) {
            button.setEnabled(on);
        }
        commandsLeftLabel.setEnabled(on);
    }
void pkg_game.UserInterface.print (String text)
Print the given text in the text area.
Parameters
text Text to display
Definition at line 74 of file UserInterface.java.
                                   {
        log.append(text);
        log.setCaretPosition(log.getDocument().getLength());
    }
void pkg_game.UserInterface.println (String text)
Print the given text plus a newline in the text area.
Parameters
text Text to display
Definition at line 83 of file UserInterface.java.
Referenced by pkg_game.GameEngine.processCommand().
                                     {
        log.append(text + "\n");
        log.setCaretPosition(log.getDocument().getLength());
    }
void pkg_game.UserInterface.processCommand () [private]
Process the command inside the text entry.
Definition at line 234 of file UserInterface.java.
Referenced by pkg_game.UserInterface.actionPerformed().
                                  {
        boolean finished = false;
        String input = entryField.getText();
        entryField.setText("");
        engine.processCommand(input);
    }
void pkg_game.UserInterface.setCommandsLeft (int commandsLeft)
Change the text for the commands left JLabel.
Parameters
commandsLeft The number of commands left
Definition at line 66 of file UserInterface.java.
                                                  {
        commandsLeftLabel.setText(" Commands left: " + commandsLeft + " ");
    }
void pkg_game.UserInterface.showImage (String imageName)
Show the image corresponding to the path of the image.
Parameters
imageName The path of the image
Definition at line 92 of file UserInterface.java.
                                            {
        URL imageURL = this.getClass().getClassLoader().getResource(imageName);
        if(imageURL == null)
            System.out.println("image not found");
        else {
            ImageIcon icon = new ImageIcon(imageURL);
            image.setIcon(icon);
            myFrame.pack();
        }
    }
Member Data Documentation
HashMap<JButton, String> pkg_game.UserInterface.buttons [private]
The list of buttons in the user interface.
Definition at line 50 of file UserInterface.java.
Referenced by pkg_game.UserInterface.createGUI(), pkg_game.UserInterface.enable(), and pkg_game.UserInterface.UserInterface().
JLabel pkg_game.UserInterface.commandsLeftLabel [private]
Container for the String of commands left.
Definition at line 45 of file UserInterface.java.
Referenced by pkg_game.UserInterface.createGUI().
GameEngine pkg_game.UserInterface.engine [private]
Gameplay handler.
Definition at line 20 of file UserInterface.java.
Referenced by pkg_game.UserInterface.UserInterface().
JTextField pkg_game.UserInterface.entryField [private]
Field where the user will put its commands.
Definition at line 30 of file UserInterface.java.
Referenced by pkg_game.UserInterface.actionPerformed(), and pkg_game.UserInterface.createGUI().
JLabel pkg_game.UserInterface.image [private]
Container for the image of the room.
Definition at line 40 of file UserInterface.java.
Referenced by pkg_game.UserInterface.createGUI().
JTextArea pkg_game.UserInterface.log [private]
Container for the displayed text.
Definition at line 35 of file UserInterface.java.
Referenced by pkg_game.UserInterface.createGUI().
JFrame pkg_game.UserInterface.myFrame [private]
JFrame containing the graphics.
Definition at line 25 of file UserInterface.java.
Referenced by pkg_game.UserInterface.createGUI().
The documentation for this class was generated from the following file:
pkg_game/UserInterface.java