pkg_world.Room Class Reference
Class used to handle a game's room.
Public Member Functions
Room (String description, String image)
Room class constructor.
Room (String description, String image, ItemList itemList, HashMap< String, Character > characters)
Room class constructor with the items.
void setExit (String direction, Room neighbor)
Define a room in a relative direction to the current room.
ItemList getContainedItems ()
containedItem field getter.
Item getItem (String name)
Return an Item through it's name.
Character getCharacter (String name)
Return an Character through it's name.
boolean hasItem (String name)
Check if the room has the given Item through it's name.
boolean hasCharacter (String name)
Check if the room has the given Character through it's name.
void addItem (Item item)
Add the given Item in the Room.
void addCharacter (Character character)
void removeItem (String itemName)
Remove the given Item to the Room.
void removeCharacter (String characterName)
Remove the given Character to the Room.
String getShortDescription ()
Getter for the description field.
String getLongDescription ()
Return the description of the room, the available exits plus the items in the room if any.
String getHumanItemsList ()
Return a human readable list of the items in the room.
String getHumanCharactersList ()
Return a human readable list of the characters in the room.
Room getExit (String direction)
Return the room in a specific direction.
Room getRandomAdjacentRoom ()
Return a random adjacent Room.
boolean isExit (Room exit)
Check if the given Room is an exit of this Room.
String getImageName ()
Getter for the imageName field.
Private Member Functions
String getHumanList (Set< String > names)
Return a human readable list of the given Set.
String getExitString ()
Return the available exits in a human readable format.
Private Attributes
String description
Description of the room.
HashMap< String, Room > exits
Collection which match a direction with the room in that direction.
String imageName
Image to display for the current room.
ItemList containedItems
Item currently being in the room.
HashMap< String, Character > containedCharacters
Characters currently bing in the room.
Detailed Description
Class used to handle a game's room.
Author
Rémi NICOLE
Definition at line 19 of file Room.java.
Constructor & Destructor Documentation
pkg_world.Room.Room (String description, String image)
Room class constructor.
Parameters
description Description for the room
image Image path to display
Definition at line 52 of file Room.java.
References pkg_world.Room.description.
                                                  {
        this(description, image, new ItemList(), new HashMap<String, Character>());
    }
pkg_world.Room.Room (String description, String image, ItemList itemList, HashMap< String, Character > characters)
Room class constructor with the items.
Parameters
description Description for the room
image Image path to display
itemList The items currently in the room
Definition at line 62 of file Room.java.
References pkg_world.Room.containedCharacters, pkg_world.Room.containedItems, pkg_world.Room.description, pkg_world.Room.exits, and pkg_world.Room.imageName.
                                                                                                           
       {
        this.description = description;
        exits = new HashMap < String, Room > ();
        imageName = image;
        containedItems = itemList;
        containedCharacters = characters;
    }
Member Function Documentation
void pkg_world.Room.addCharacter (Character character)
Definition at line 127 of file Room.java.
                                                  {
        containedCharacters.put(character.getName(), character);
    }
void pkg_world.Room.addItem (Item item)
Add the given Item in the Room.
Parameters
item Item to be added
Definition at line 123 of file Room.java.
                                   {
        containedItems.put(item.getName(), item);
    }
Character pkg_world.Room.getCharacter (String name)
Return an Character through it's name.
Returns
The wanted Character
Definition at line 99 of file Room.java.
                                               {
        return containedCharacters.get(name);
    }
ItemList pkg_world.Room.getContainedItems ()
containedItem field getter.
Returns
The Room's inventory
Definition at line 83 of file Room.java.
References pkg_world.Room.containedItems.
                                        {
        return containedItems;
    }
Room pkg_world.Room.getExit (String direction)
Return the room in a specific direction.
Parameters
direction The direction of the wanted room
Returns
The wanted Room
Definition at line 227 of file Room.java.
                                          {
        return exits.get(direction);
    }
String pkg_world.Room.getExitString () [private]
Return the available exits in a human readable format.
Returns
The available exits in a human readable format
Definition at line 215 of file Room.java.
References pkg_world.Room.exits.
Referenced by pkg_world.Room.getLongDescription().
                                   {
        StringBuilder returnString = new StringBuilder("Exits:");
        for(String vS:exits.keySet())
            returnString.append(" " + vS);
        return returnString.toString();
    }
String pkg_world.Room.getHumanCharactersList ()
Return a human readable list of the characters in the room.
Returns
The list of the items
Definition at line 179 of file Room.java.
References pkg_world.Room.containedCharacters, and pkg_world.Room.getHumanList().
Referenced by pkg_world.Room.getLongDescription().
                                           {
        return getHumanList(containedCharacters.keySet());
    }
String pkg_world.Room.getHumanItemsList ()
Return a human readable list of the items in the room.
Returns
The list of the items
Definition at line 171 of file Room.java.
References pkg_world.Room.containedItems, and pkg_world.Room.getHumanList().
Referenced by pkg_world.Room.getLongDescription().
                                      {
        return getHumanList(containedItems.keySet());
    }
String pkg_world.Room.getHumanList (Set< String > names) [private]
Return a human readable list of the given Set.
Parameters
names Set to display.
Returns
The list of the items
Definition at line 188 of file Room.java.
Referenced by pkg_world.Room.getHumanCharactersList(), and pkg_world.Room.getHumanItemsList().
                                                   {
        String returnString = "";
        Iterator<String> it = names.iterator();
        while(it.hasNext()) {
            String itemName = it.next();
            // If the item's name begins with a vowel, the prefix is ' an '
            // if not, the prefix is ' a '
            String prefix = " a" + (((new String("aeiouy")).contains(itemName.substring(0,1)))? "n" : "") +
       " ";
            if(returnString.equals(""))
                returnString += prefix + itemName;
            else {
                // Check if it is the last item
                if(it.hasNext())
                    returnString += "," + prefix + itemName;
                else
                    returnString += " and" + prefix + itemName;
            }
        }
        return returnString;
    }
String pkg_world.Room.getImageName ()
Getter for the imageName field.
Returns
The name of the Room's image representation
Definition at line 263 of file Room.java.
References pkg_world.Room.imageName.
                                 {
        return "Images/" + imageName;
    }
Item pkg_world.Room.getItem (String name)
Return an Item through it's name.
Returns
The wanted Item
Definition at line 91 of file Room.java.
                                     {
        return containedItems.get(name);
    }
String pkg_world.Room.getLongDescription ()
Return the description of the room, the available exits plus the items in the room if any.
Returns
The description.
Definition at line 160 of file Room.java.
References pkg_world.Room.containedCharacters, pkg_world.Room.description, pkg_world.Room.getExitString(), pkg_world.Room.getHumanCharactersList(), and pkg_world.Room.getHumanItemsList().
                                       {
        return "You are " + description + ".\n"
                + ((!containedItems.isEmpty())? "You can see" +
      getHumanItemsList() + " near you.\n" : "")
                + ((!containedCharacters.isEmpty())? "You can hear" +
      getHumanCharactersList() + " moving near you\n" : "")
                + getExitString();
    }
Room pkg_world.Room.getRandomAdjacentRoom ()
Return a random adjacent Room.
Returns
The wanted Room
Definition at line 235 of file Room.java.
References pkg_world.Room.exits, and pkg_game.GameEngine.getRooms().
                                        {
        Room nextRoom;
        do {
            // Convertit les valeurs en tableau primitif de Room
            // cf. http://docs.oracle.com/javase/8/docs/api/java/util/Collection.html#toArray-T:A-
            nextRoom = exits.values().toArray(new Room[0])[
                // Valeur aléatoire entre 0 et la taille du tableau (exclus)
                (new Random()).nextInt(exits.values().size())
                ];
            // prevent the character from going to the random room
        } while (nextRoom == GameEngine.getRooms().get(0));
        return nextRoom;
    }
String pkg_world.Room.getShortDescription ()
Getter for the description field.
Returns
The description field
Definition at line 151 of file Room.java.
References pkg_world.Room.description.
                                        {
        return description;
    }
boolean pkg_world.Room.hasCharacter (String name)
Check if the room has the given Character through it's name.
Returns
True if this Room has the Character
Definition at line 115 of file Room.java.
                                             {
        return containedCharacters.containsKey(name);
    }
boolean pkg_world.Room.hasItem (String name)
Check if the room has the given Item through it's name.
Returns
True if this Room has the Item
Definition at line 107 of file Room.java.
                                        {
        return containedItems.containsKey(name);
    }
boolean pkg_world.Room.isExit (Room exit)
Check if the given Room is an exit of this Room.
Parameters
exit The Room to check
Returns
True if the given Room is an exit of this Room
Definition at line 255 of file Room.java.
                                     {
        return exits.containsValue(exit);
    }
void pkg_world.Room.removeCharacter (String characterName)
Remove the given Character to the Room.
Parameters
characterName Character to be removed
Definition at line 143 of file Room.java.
                                                      {
        containedCharacters.remove(characterName);
    }
void pkg_world.Room.removeItem (String itemName)
Remove the given Item to the Room.
Parameters
itemName Item to be removed
Definition at line 135 of file Room.java.
                                            {
        containedItems.remove(itemName);
    }
void pkg_world.Room.setExit (String direction, Room neighbor)
Define a room in a relative direction to the current room.
Parameters
direction Direction in which the room is.
neighbor The room in that direction.
Definition at line 75 of file Room.java.
                                                         {
        exits.put(direction, neighbor);
    }
Member Data Documentation
HashMap<String, Character> pkg_world.Room.containedCharacters [private]
Characters currently bing in the room.
Definition at line 45 of file Room.java.
Referenced by pkg_world.Room.getHumanCharactersList(), pkg_world.Room.getLongDescription(), and pkg_world.Room.Room().
ItemList pkg_world.Room.containedItems [private]
Item currently being in the room.
Definition at line 40 of file Room.java.
Referenced by pkg_world.Room.getContainedItems(), pkg_world.Room.getHumanItemsList(), and pkg_world.Room.Room().
String pkg_world.Room.description [private]
Description of the room.
Definition at line 24 of file Room.java.
Referenced by pkg_world.Room.getLongDescription(), pkg_world.Room.getShortDescription(), and pkg_world.Room.Room().
HashMap<String, Room> pkg_world.Room.exits [private]
Collection which match a direction with the room in that direction.
Definition at line 30 of file Room.java.
Referenced by pkg_world.Room.getExitString(), pkg_world.Room.getRandomAdjacentRoom(), and pkg_world.Room.Room().
String pkg_world.Room.imageName [private]
Image to display for the current room.
Definition at line 35 of file Room.java.
Referenced by pkg_world.Room.getImageName(), and pkg_world.Room.Room().
The documentation for this class was generated from the following file:
pkg_world/Room.java