pkg_commands.BeamerCommand Class Reference
class BeamerCommand used to teleport into a remembered room
Public Member Functions
BeamerCommand ()
Constructor for BeamerCommand.
boolean execute (Player player) throws NoArgumentException,pkg_exceptions.IllegalArgumentException,UnauthorizedException
Teleport to the remembered room or remember a room.
void charge (Player player)
Remember the current room.
Private Member Functions
void teleport (Player player) throws UnauthorizedException
Teleport the player to the remembered room.
Additional Inherited Members
Detailed Description
class BeamerCommand used to teleport into a remembered room
Author
Rémi NICOLE
Definition at line 10 of file BeamerCommand.java.
Constructor & Destructor Documentation
pkg_commands.BeamerCommand.BeamerCommand ()
Constructor for BeamerCommand.
Definition at line 15 of file BeamerCommand.java.
                          {
    }
Member Function Documentation
void pkg_commands.BeamerCommand.charge (Player player)
Remember the current room.
Parameters
player The player that called this command
Definition at line 67 of file BeamerCommand.java.
References pkg_world.Player.getBeamerRoom(), and pkg_commands.Command.setMessage().
Referenced by pkg_commands.BeamerCommand.execute().
                                      {
        if(player.getBeamerRoom() == null)
            setMessage("Useless room remembered.");
        else
            setMessage("Useful room overridden by a useless room.");
        player.setBeamerRoom(player.getCurrentRoom());
    }
boolean pkg_commands.BeamerCommand.execute (Player player) throws NoArgumentException,pkg_exceptions.IllegalArgumentException,UnauthorizedException
Teleport to the remembered room or remember a room.
It teleports to the remembered room if the command parameter was `teleport`, and it remembers the room if the command parameter was `charge`
Parameters
player The player that called this command
Exceptions
NoArgumentException When the user typed the command without parameter
IllegalArgumentException When the user typed a parameter other than `teleport` or `charge`
UnauthorizedException When the user tries to teleport to null
Returns
False because it is not the quit command
Definition at line 30 of file BeamerCommand.java.
References pkg_commands.BeamerCommand.charge(), pkg_commands.Command.getParameter(), pkg_commands.Command.hasParameter(), and pkg_commands.BeamerCommand.teleport().
                                                                                                           
                              {
        if(hasParameter()) {
            if(getParameter().equals("charge")) {
                charge(player);
                return false;
            } else if(getParameter().equals("teleport")) {
                teleport(player);
                return false;
            } else {
                throw new pkg_exceptions.IllegalArgumentException("
      In order to do that, I may need to upgrade. But I don't want to.");
            }
        } else
            throw new NoArgumentException("You can either charge or teleport with the
       beamer.\nBut that may be too much complicated for you, isn't it?");
    }
void pkg_commands.BeamerCommand.teleport (Player player) throws UnauthorizedException [private]
Teleport the player to the remembered room.
Parameters
player The player that called this command
Exceptions
UnauthorizedException When the user tries to teleport to null
Definition at line 50 of file BeamerCommand.java.
References pkg_commands.GoCommand.goRoomNoCheck(), and pkg_commands.Command.setMessage().
Referenced by pkg_commands.BeamerCommand.execute().
                                                                      {
        try {
            if(player.getBeamerRoom() == player.getCurrentRoom())
                setMessage("Teleporting you right were you are.");
            else
                setMessage("Teleporting you to useless room...");
            goRoomNoCheck(player.getBeamerRoom(), player, false);
        } catch(pkg_exceptions.IllegalArgumentException e) {
            // Tried to teleport to null
            throw new UnauthorizedException("I'm sorry but I can't teleport you
       nowhere.");
        }
    }
The documentation for this class was generated from the following file:
pkg_commands/BeamerCommand.java