pkg_commands.Command Class Reference
Class used to handle a command of one or two words.
Public Member Functions
String getParameter ()
Parameter field getter.
String getSecondParameter ()
Second Parameter field getter.
void setParameter (String parameter)
Parameter field setter.
void setSecondParameter (String parameter)
Second Parameter field setter.
boolean hasParameter ()
Return true if the parameter is null.
boolean hasSecondParameter ()
Return true if the second parameter is null.
String getMessage ()
Message field getter.
boolean hasMessage ()
Return true if the message is equal to null or ``.
abstract boolean execute (Player player) throws NoArgumentException,pkg_exceptions.IllegalArgumentException,UnauthorizedException
Process the command.
Protected Member Functions
void setMessage (String message)
Message field setter.
Private Attributes
String parameter
Parameter for the command.
String secondParameter
Second parameter for the command.
String message
Message to be printed.
Detailed Description
Class used to handle a command of one or two words.
Author
Rémi NICOLE
Definition at line 14 of file Command.java.
Member Function Documentation
abstract boolean pkg_commands.Command.execute (Player player) throws NoArgumentException,pkg_exceptions.IllegalArgumentException,UnauthorizedException [abstract]
Process the command.
Parameters
player The player that called this command
Exceptions
NoArgumentException When the command needed a parameter but the user didn't specify one
IllegalArgumentException When the user typed a parameter other than the correct ones
UnauthorizedException When the user isn't allowed to do this action
String pkg_commands.Command.getMessage ()
Message field getter.
Returns
The message to print to the user
Definition at line 97 of file Command.java.
References pkg_commands.Command.message.
Referenced by pkg_commands.TestCommand.execute(), pkg_commands.HelpCommand.execute(), and pkg_commands.GoCommand.goRoomNoCheck().
                               {
        return (message == null)? "" : message;
    }
String pkg_commands.Command.getParameter ()
Parameter field getter.
Returns
The parameter given by the user
Definition at line 41 of file Command.java.
References pkg_commands.Command.parameter.
Referenced by pkg_commands.LookCommand.execute(), pkg_commands.TalkCommand.execute(), pkg_commands.DropCommand.execute(), pkg_commands.TakeCommand.execute(), pkg_commands.EatCommand.execute(), pkg_commands.GiveCommand.execute(), pkg_commands.BeamerCommand.execute(), pkg_commands.TestCommand.execute(), and pkg_commands.GoCommand.execute().
                                 {
        return parameter;
    }
String pkg_commands.Command.getSecondParameter ()
Second Parameter field getter.
Returns
The second parameter given by the user
Definition at line 49 of file Command.java.
References pkg_commands.Command.secondParameter.
Referenced by pkg_commands.GiveCommand.execute().
                                       {
        return secondParameter;
    }
boolean pkg_commands.Command.hasMessage ()
Return true if the message is equal to null or ``.
Returns
True if the message is equal to null or ``
Definition at line 105 of file Command.java.
References pkg_commands.Command.message.
Referenced by pkg_commands.GoCommand.goRoomNoCheck().
                                {
        return (message == null) ? false : !message.equals("");
    }
boolean pkg_commands.Command.hasParameter ()
Return true if the parameter is null.
Returns
True if the parameter is null
Definition at line 73 of file Command.java.
References pkg_commands.Command.parameter.
Referenced by pkg_commands.LookCommand.execute(), pkg_commands.TalkCommand.execute(), pkg_commands.DropCommand.execute(), pkg_commands.TakeCommand.execute(), pkg_commands.EatCommand.execute(), pkg_commands.GiveCommand.execute(), pkg_commands.BeamerCommand.execute(), pkg_commands.TestCommand.execute(), and pkg_commands.GoCommand.execute().
                                  {
        return (parameter != null);
    }
boolean pkg_commands.Command.hasSecondParameter ()
Return true if the second parameter is null.
Returns
True if the second parameter is null
Definition at line 81 of file Command.java.
References pkg_commands.Command.secondParameter.
Referenced by pkg_commands.GiveCommand.execute().
                                        {
        return (secondParameter != null);
    }
void pkg_commands.Command.setMessage (String message) [protected]
Message field setter.
Parameters
message The message to set
Definition at line 89 of file Command.java.
References pkg_commands.Command.message.
Referenced by pkg_commands.BeamerCommand.charge(), pkg_commands.InventoryCommand.execute(), pkg_commands.CreditsCommand.execute(), pkg_commands.LookCommand.execute(), pkg_commands.DropCommand.execute(), pkg_commands.TalkCommand.execute(), pkg_commands.TakeCommand.execute(), pkg_commands.EatCommand.execute(), pkg_commands.GiveCommand.execute(), pkg_commands.GoCommand.execute(), pkg_commands.TestCommand.execute(), pkg_commands.HelpCommand.execute(), pkg_commands.GoCommand.goRoomNoCheck(), and pkg_commands.BeamerCommand.teleport().
                                              {
        this.message = message;
    }
void pkg_commands.Command.setParameter (String parameter)
Parameter field setter.
Parameters
parameter The parameter to set
Definition at line 57 of file Command.java.
References pkg_commands.Command.parameter.
                                               {
        this.parameter = parameter;
    }
void pkg_commands.Command.setSecondParameter (String parameter)
Second Parameter field setter.
Parameters
parameter The second parameter to set
Definition at line 65 of file Command.java.
References pkg_commands.Command.parameter, and pkg_commands.Command.secondParameter.
                                                     {
        secondParameter = parameter;
    }
Member Data Documentation
String pkg_commands.Command.message [private]
Message to be printed.
This message is printed if and only if the command was successfully processed
Definition at line 35 of file Command.java.
Referenced by pkg_commands.Command.getMessage(), pkg_commands.Command.hasMessage(), and pkg_commands.Command.setMessage().
String pkg_commands.Command.parameter [private]
Parameter for the command.
It equals to null if there is no parameter.
Definition at line 21 of file Command.java.
Referenced by pkg_commands.Command.getParameter(), pkg_commands.Command.hasParameter(), pkg_commands.Command.setParameter(), and pkg_commands.Command.setSecondParameter().
String pkg_commands.Command.secondParameter [private]
Second parameter for the command.
Equals to null if there is no second parameter
Definition at line 28 of file Command.java.
Referenced by pkg_commands.Command.getSecondParameter(), pkg_commands.Command.hasSecondParameter(), and pkg_commands.Command.setSecondParameter().
The documentation for this class was generated from the following file:
pkg_commands/Command.java