pkg_commands.GiveCommand Class Reference
Public Member Functions
GiveCommand ()
boolean execute (Player player) throws NoArgumentException,pkg_exceptions.IllegalArgumentException,UnauthorizedException
Additional Inherited Members
Detailed Description
class GiveCommand used to make the Player give an Item
Author
Rémi Nicole
Definition at line 12 of file GiveCommand.java.
Constructor & Destructor Documentation
pkg_commands.GiveCommand.GiveCommand ()
Constructor for GiveCommand
Definition at line 17 of file GiveCommand.java.
                        {
    }
Member Function Documentation
boolean pkg_commands.GiveCommand.execute (Player player) throws NoArgumentException,pkg_exceptions.IllegalArgumentException,UnauthorizedException
Make the player give an Item to a Character.
Parameters
player The player that called this command
Exceptions
NoArgumentException When the user typed the command without parameter or with only one parameter
IllegalArgumentException When the user typed an Item or Character name other than any of the items or characters in the Room
UnauthorizedException When the Character doesn't want the Item or any Item
Returns
False because it is not the quit command
Definition at line 29 of file GiveCommand.java.
References pkg_commands.Command.getParameter(), pkg_commands.Command.getSecondParameter(), pkg_commands.Command.hasParameter(), pkg_commands.Command.hasSecondParameter(), pkg_world.pkg_characters.Character.isSatisfied(), pkg_commands.Command.setMessage(), pkg_world.pkg_characters.Character.takeItem(), and pkg_world.pkg_characters.Character.wantsItem().
                                                                                                           
                              {
        if(hasParameter()) {
            if(player.getCurrentRoom().hasCharacter(getParameter())) {
                Character character = player.getCurrentRoom().getCharacter(
      getParameter());
                if(hasSecondParameter()) {
                    if(player.hasItem(getSecondParameter())) {
                        Item item = player.getItem(getSecondParameter());
                        if(!character.isSatisfied()) {
                            if(character.wantsItem(item)) {
                                setMessage(character.takeItem(item));
                                player.eatObject(getSecondParameter());
                            } else {
                                String failureMessage = character.takeItem(item);
                                throw new UnauthorizedException((failureMessage ==
      null)? "He doesn't want anything from you. He's smart." : failureMessage);
                            }
                        } else
                            throw new UnauthorizedException("He already used you,
       remember? No, of course not.");
                    } else
                        throw new pkg_exceptions.IllegalArgumentException
      ("I'm not sure you want to give that.");
                } else
                    throw new NoArgumentException("I'm afraid giving yourself to this
       one won't be enough. Again.");
            } else
                throw new pkg_exceptions.IllegalArgumentException("
      Still trying to give something to your imaginary friend?");
        } else
            throw new NoArgumentException("Would you give a try to instead give
       something to someone?");
        return false;
    }
The documentation for this class was generated from the following file:
pkg_commands/GiveCommand.java