pkg_commands.DropCommand Class Reference
Public Member Functions
DropCommand ()
boolean execute (Player player) throws NoArgumentException,IllegalArgumentException
Additional Inherited Members
Detailed Description
class DropCommand used to make the player drop an Item
Author
Rémi Nicole
Definition at line 11 of file DropCommand.java.
Constructor & Destructor Documentation
pkg_commands.DropCommand.DropCommand ()
Constructor for DropCommand
Definition at line 16 of file DropCommand.java.
                        {
    }
Member Function Documentation
boolean pkg_commands.DropCommand.execute (Player player) throws NoArgumentException,IllegalArgumentException
Drop the Item through it's name in the parameter field.
Parameters
player The player that called this command
Exceptions
NoArgumentException When the user typed the command without parameter
IllegalArgumentException When the user typed a name other than any of the items in the Player's inventory
Returns
False because it is not the quit command
Definition at line 27 of file DropCommand.java.
References pkg_commands.Command.getParameter(), pkg_commands.Command.hasParameter(), and pkg_commands.Command.setMessage().
                                                                                              {
        if(hasParameter()) {
            if(player.hasItem(getParameter())){
                player.dropObject(getParameter());
                setMessage("Oh, dear. He took a" + (((new String("aeiouy")).contains(
      getParameter().substring(0,1)))? "n " : " ") + getParameter() + ".");
            } else
                throw new IllegalArgumentException("If you want to drop that, you may have a mental
       disorder. As expected.");
        } else
            throw new NoArgumentException("I agree. We both want you to drop dead.");
        return false;
    }
The documentation for this class was generated from the following file:
pkg_commands/DropCommand.java