pkg_world.pkg_characters.Character Class Reference
class Character
Public Member Functions
Character (final String name)
Constructor for Character with name only.
Character (final String name, final String dialog)
Constructor for Character with name and dialog only.
Character (final String name, final String dialog, Item wantedItem, final String successAction, final String failureAction)
Constructor for Character.
void addDialog (final String dialog)
Add a possible dialog.
String talk ()
A dialog to be displayed.
String takeItem (Item item)
Try to give him an Item.
boolean wantsItem (Item item)
Returns true if the given Item is wanted by the creature/character.
String getName ()
Name field getter.
boolean isSatisfied ()
Detailed Description
class Character
Author
Rémi Nicole
Definition at line 17 of file Character.java.
Constructor & Destructor Documentation
pkg_world.pkg_characters.Character.Character (final String name)
Constructor for Character with name only.
When using this constructor only, the creature/character says nothing and wants nothing.
Parameters
name The name of the creature/character
Definition at line 62 of file Character.java.
                                       {
        this.name = name;
        satisfied = false;
        dialogs = new ArrayList<String>();
    }
pkg_world.pkg_characters.Character.Character (final String name, final String dialog)
Constructor for Character with name and dialog only.
When using this constructor only, the creature/character wants nothing.
Parameters
name The name of the creature/character
dialog The dialog displayed when talking to it/him/her
Definition at line 75 of file Character.java.
                                                             {
        this(name);
        dialogs.add(dialog);
    }
pkg_world.pkg_characters.Character.Character (final String name, final String dialog, Item wantedItem, final String successAction, final String failureAction)
Constructor for Character.
Parameters
name The name of the creature/character
dialog The dialog displayed when talking to it/him/her
wantedItem Item wanted by the creature/character
Definition at line 86 of file Character.java.
                                                                                                           
                                 {
        this(name, dialog);
        this.wantedItem = wantedItem;
        this.successAction = successAction;
        this.failureAction = failureAction;
    }
Member Function Documentation
void pkg_world.pkg_characters.Character.addDialog (final String dialog)
Add a possible dialog.
Parameters
dialog The dialog to add
Definition at line 97 of file Character.java.
                                               {
        dialogs.add(dialog);
    }
String pkg_world.pkg_characters.Character.getName ()
Name field getter.
Returns
The name of the creature/character
Definition at line 132 of file Character.java.
Referenced by pkg_world.pkg_characters.MovingCharacter.move().
                            {
        return name;
    }
boolean pkg_world.pkg_characters.Character.isSatisfied ()
Definition at line 136 of file Character.java.
Referenced by pkg_commands.GiveCommand.execute().
                                 {
        return satisfied;
    }
String pkg_world.pkg_characters.Character.takeItem (Item item)
Try to give him an Item.
Returns
An action to be displayed in case of success or failure
Definition at line 113 of file Character.java.
Referenced by pkg_commands.GiveCommand.execute().
                                      {
        if(wantedItem == item)
            satisfied = true;
        return (wantedItem == item) ? successAction : failureAction;
    }
String pkg_world.pkg_characters.Character.talk ()
A dialog to be displayed.
Returns
A random dialog from the dialogs field
Definition at line 105 of file Character.java.
                         {
        return (dialogs.isEmpty())? "He doesn't want to talk to you. I understand him." : dialogs.get((new
      Random()).nextInt(dialogs.size()));
    }
boolean pkg_world.pkg_characters.Character.wantsItem (Item item)
Returns true if the given Item is wanted by the creature/character.
Parameters
item The Item to check
Returns
true if item is equal to the wantedItem field
Definition at line 124 of file Character.java.
Referenced by pkg_commands.GiveCommand.execute().
                                        {
        return wantedItem == item;
    }
The documentation for this class was generated from the following file:
pkg_world/pkg_characters/Character.java