pkg_world.Player Class Reference
class Player used to handle the user's player.
Public Member Functions
Player (String name, Room firstRoom)
Player class constructor.
String getName ()
name field getter.
int getMaxWeight ()
maxWeight field getter.
void setMaxWeight (int maxWeight)
maxWeight field setter.
Room getCurrentRoom ()
currentRoom field getter.
void goRoom (Room room)
Go to the given room.
Room getPreviousRoom ()
Return the last Room.
void pushPreviousRooms (Room room)
Push a room in the previousRooms stack.
void pushForward ()
Push the currentRoom in the previousRooms stack.
void popPreviousRooms ()
Pop the last room in the previousRooms stack.
boolean noPreviousRooms ()
Return true if there is no previous rooms.
void setBeamerRoom (Room beamerRoom)
beamerRoom field setter.
Room getBeamerRoom ()
beamerRoom field getter.
Item getItem (String item)
Return the Item in the player's inventory through it's name.
boolean hasItem (String item)
Check if the player has a given Item.
boolean canCarry (Item item)
Check if the player can carry the given Item.
void takeObject (Item item)
Take the given object.
void dropObject (String item)
Drop the given object.
void eatObject (String itemName)
Destroy an object.
String getInventory ()
Return a String containing information about the items carried by the player.
boolean threwSnowball ()
Return true if the player already threw a snowball.
void throwSnowball ()
Set the threwSnowball field to true.
Detailed Description
class Player used to handle the user's player.
Author
Rémi Nicole
Definition at line 20 of file Player.java.
Constructor & Destructor Documentation
pkg_world.Player.Player (String name, Room firstRoom)
Player class constructor.
Parameters
name The name of the player
firstRoom Room where the player start
Definition at line 68 of file Player.java.
References pkg_world.Player.threwSnowball().
                                               {
        threwSnowball = false;
        this.name = name;
        backpack = new ItemList();
        backpackWeight = 0;
        currentRoom = firstRoom;
        previousRooms = new Stack<Room>();
    }
Member Function Documentation
boolean pkg_world.Player.canCarry (Item item)
Check if the player can carry the given Item.
This methods simply checks the Item with it's weight
Parameters
item The Item to be checked
Returns
True if the Item can be carried
Definition at line 194 of file Player.java.
                                       {
        return backpackWeight + item.getWeight() < maxWeight;
    }
void pkg_world.Player.dropObject (String item)
Drop the given object.
Parameters
item Item to be dropped
Definition at line 211 of file Player.java.
                                        {
        backpackWeight -= backpack.get(item).getWeight();
        backpack.transfer(item, currentRoom.getContainedItems());
    }
void pkg_world.Player.eatObject (String itemName)
Destroy an object.
Parameters
itemName Item to be destroyed.
Definition at line 220 of file Player.java.
                                           {
        backpack.remove(itemName);
    }
Room pkg_world.Player.getBeamerRoom ()
beamerRoom field getter.
Returns
The saved Room by the beamer
Definition at line 167 of file Player.java.
Referenced by pkg_commands.BeamerCommand.charge().
                                {
        return beamerRoom;
    }
Room pkg_world.Player.getCurrentRoom ()
currentRoom field getter.
Returns
The Room where the player is currently in
Definition at line 105 of file Player.java.
Referenced by pkg_game.GameEngine.processCommand().
                                 {
        return currentRoom;
    }
String pkg_world.Player.getInventory ()
Return a String containing information about the items carried by the player.
Returns
String The inventory
Definition at line 229 of file Player.java.
Referenced by pkg_commands.InventoryCommand.execute().
                                 {
        String returnString = "";
        Set<String> itemsNames = backpack.keySet();
        Iterator<String> it = itemsNames.iterator();
        while(it.hasNext()) {
            String itemName = it.next();
            // If the item's name begins with a vowel, the prefix is ' an '
            // if not, the prefix is ' a '
            String prefix = " a" + (((new String("aeiouy")).contains(itemName.substring(0,1)))? "n" : "") +
       " ";
            if(returnString.equals(""))
                returnString += prefix + itemName;
            else {
                // Check if it is the last item
                if(it.hasNext())
                    returnString += "," + prefix + itemName;
                else
                    returnString += " and" + prefix + itemName;
            }
        }
        return (returnString.equals(""))?
            "You have nothing. This may be a metaphor for your life.\nBut as always you didn't understand a
       word I said, don't you?"
            : "You have" + returnString + ".\nCan't you remember that?";
    }
Item pkg_world.Player.getItem (String item)
Return the Item in the player's inventory through it's name.
Parameters
item The name of the Item
Returns
The asked Item
Definition at line 176 of file Player.java.
                                     {
        return backpack.get(item);
    }
int pkg_world.Player.getMaxWeight ()
maxWeight field getter.
Returns
The maximum weight the player can carry
Definition at line 89 of file Player.java.
                              {
        return maxWeight;
    }
String pkg_world.Player.getName ()
name field getter.
Returns
The name of the player
Definition at line 81 of file Player.java.
                            {
        return name;
    }
Room pkg_world.Player.getPreviousRoom ()
Return the last Room.
Returns
The last Room were the Player was
Definition at line 121 of file Player.java.
                                  {
        return (previousRooms.empty())? null : previousRooms.peek();
    }
void pkg_world.Player.goRoom (Room room)
Go to the given room.
Parameters
room Room to go to
Definition at line 113 of file Player.java.
                                  {
        currentRoom = room;
    }
boolean pkg_world.Player.hasItem (String item)
Check if the player has a given Item.
Parameters
item Item name to be checked
Definition at line 184 of file Player.java.
                                        {
        return backpack.containsKey(item);
    }
boolean pkg_world.Player.noPreviousRooms ()
Return true if there is no previous rooms.
Returns
True if there is no previous rooms
Definition at line 151 of file Player.java.
                                     {
        return previousRooms.empty();
    }
void pkg_world.Player.popPreviousRooms ()
Pop the last room in the previousRooms stack.
Definition at line 143 of file Player.java.
                                   {
        previousRooms.pop();
    }
void pkg_world.Player.pushForward ()
Push the currentRoom in the previousRooms stack.
Definition at line 136 of file Player.java.
                              {
        previousRooms.push(currentRoom);
    }
void pkg_world.Player.pushPreviousRooms (Room room)
Push a room in the previousRooms stack.
Parameters
room Room to be pushed
Definition at line 129 of file Player.java.
                                             {
        previousRooms.push(room);
    }
void pkg_world.Player.setBeamerRoom (Room beamerRoom)
beamerRoom field setter.
Parameters
beamerRoom The beamer Room to be saved
Definition at line 159 of file Player.java.
                                               {
        this.beamerRoom = beamerRoom;
    }
void pkg_world.Player.setMaxWeight (int maxWeight)
maxWeight field setter.
Parameters
maxWeight The value for the maxWeight field
Definition at line 97 of file Player.java.
                                            {
        this.maxWeight = maxWeight;
    }
void pkg_world.Player.takeObject (Item item)
Take the given object.
Parameters
item Item to be taken.
Definition at line 202 of file Player.java.
References pkg_world.pkg_items.Item.getName().
                                      {
        currentRoom.getContainedItems().transfer(item.getName(), backpack);
        backpackWeight += item.getWeight();
    }
boolean pkg_world.Player.threwSnowball ()
Return true if the player already threw a snowball.
Returns
The threwSnowball field
Definition at line 258 of file Player.java.
Referenced by pkg_world.Player.Player(), and pkg_world.Player.throwSnowball().
                                   {
        return threwSnowball;
    }
void pkg_world.Player.throwSnowball ()
Set the threwSnowball field to true.
Definition at line 265 of file Player.java.
References pkg_world.Player.threwSnowball().
                                {
        threwSnowball = true;
    }
The documentation for this class was generated from the following file:
pkg_world/Player.java