pkg_commands.EatCommand Class Reference
Public Member Functions
EatCommand ()
boolean execute (Player player) throws NoArgumentException,pkg_exceptions.IllegalArgumentException,UnauthorizedException
Additional Inherited Members
Detailed Description
class EatCommand used to make the player eat an object.
Author
Rémi Nicole
Definition at line 10 of file EatCommand.java.
Constructor & Destructor Documentation
pkg_commands.EatCommand.EatCommand ()
Constructor for EatCommand
Definition at line 15 of file EatCommand.java.
                       {
    }
Member Function Documentation
boolean pkg_commands.EatCommand.execute (Player player) throws NoArgumentException,pkg_exceptions.IllegalArgumentException,UnauthorizedException
Make the player eat an object. Only the `magiccookie` Item is eatable
Parameters
player The player that called this command
Exceptions
NoArgumentException When the user typed the command without parameter
IllegalArgumentException When the user typed a name other than any of the items in the Player's inventory
UnauthorizedException When the user tries to eat a non-eatable object
Returns
False because it is not the quit command
Definition at line 28 of file EatCommand.java.
References pkg_commands.Command.getParameter(), pkg_commands.Command.hasParameter(), and pkg_commands.Command.setMessage().
                                                                                                           
                              {
        if(hasParameter()) {
            if(player.hasItem(getParameter())){
                if(getParameter().equals("magiccookie")) {
                    player.eatObject(getParameter());
                    player.setMaxWeight(player.getMaxWeight() + 100);
                    setMessage("You found an out of date \"magic\" cookie inside a cave and you
       just ate it.\nNow you can carry more items. That's logic!");
                } else
                    throw new UnauthorizedException("If that's what you eat, I don't
       want to be invited to any of your meals.\nI'm afraid I can't allow you to do that.");
            } else
                throw new pkg_exceptions.IllegalArgumentException("
      You don't have that. And I'm sure that if you did, it wouldn't be smart to eat that.");
        } else
            throw new NoArgumentException("Eat my shorts?");
        return false;
    }
The documentation for this class was generated from the following file:
pkg_commands/EatCommand.java