pkg_commands.TalkCommand Class Reference
class TalkCommand used to talk to a Character
Public Member Functions
TalkCommand ()
Constructor for TalkCommand.
boolean execute (Player player) throws NoArgumentException,IllegalArgumentException
Make the player talk to a Character.
Additional Inherited Members
Detailed Description
class TalkCommand used to talk to a Character
Author
Rémi Nicole
Definition at line 11 of file TalkCommand.java.
Constructor & Destructor Documentation
pkg_commands.TalkCommand.TalkCommand ()
Constructor for TalkCommand.
Definition at line 16 of file TalkCommand.java.
                        {
    }
Member Function Documentation
boolean pkg_commands.TalkCommand.execute (Player player) throws NoArgumentException,IllegalArgumentException
Make the player talk to a Character.
Parameters
player The player that called this command
Exceptions
NoArgumentException When the user typed the command without parameter
IllegalArgumentException When the user typed a name other than any of the characters in the Room
Returns
False because it is not the quit command
Definition at line 27 of file TalkCommand.java.
References pkg_commands.Command.getParameter(), pkg_commands.Command.hasParameter(), and pkg_commands.Command.setMessage().
                                                                                              {
        if(hasParameter()) {
            if(player.getCurrentRoom().hasCharacter(getParameter())){
                setMessage(player.getCurrentRoom().getCharacter(
      getParameter()).talk());
            } else if(player.getCurrentRoom().hasItem(getParameter()))
                throw new IllegalArgumentException("It's a" + (((new String("aeiouy")).contains(
      getParameter().substring(0,1)))? "n " : " ") + getParameter() + "! Why would you
       want to talk to that!");
            else
                throw new IllegalArgumentException("Your imaginary friend is not here. He might have left
       you.");
        } else
            throw new NoArgumentException("Talking alone won't make you more clever.");
        return false;
    }
The documentation for this class was generated from the following file:
pkg_commands/TalkCommand.java